# Generated by Django 6.0.3 on 2026-03-28 19:33

import bankapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='checking_account_number',
            field=models.CharField(default=bankapp.models.generate_account_number, max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='checking_balance',
            field=models.DecimalField(decimal_places=2, default=42500.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='savings_account_number',
            field=models.CharField(default=bankapp.models.generate_account_number, max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='savings_balance',
            field=models.DecimalField(decimal_places=2, default=150000.0, max_digits=12),
        ),
    ]
