# Generated by Django 4.2.9 on 2026-03-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0007_userprofile_savings_apy_alter_chatmessage_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='verification_docs/'),
        ),
    ]
