# Generated by Django 4.2.9 on 2026-03-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0009_userprofile_address_line1_userprofile_citizenship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='previous_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
