# Generated by Django 4.2.9 on 2026-03-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0010_userprofile_last_login_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='transferhistory',
            name='transaction_type',
            field=models.CharField(default='Transfer', max_length=20),
        ),
    ]
