# Generated by Django 4.2.9 on 2026-03-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0011_recentrecipient_transferhistory_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='verification_document',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_back',
            field=models.ImageField(blank=True, null=True, upload_to='verification_docs/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_front',
            field=models.ImageField(blank=True, null=True, upload_to='verification_docs/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
