# Generated by Django 4.2.9 on 2026-03-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0012_remove_userprofile_verification_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id_type',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id_back',
            field=models.FileField(blank=True, null=True, upload_to='verification_docs/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id_front',
            field=models.FileField(blank=True, null=True, upload_to='verification_docs/'),
        ),
    ]
