from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('about/', views.about, name='about'),
    path('personal/', views.personal, name='personal'),
    path('business/', views.business, name='business'),
    path('register/', views.register, name='register'),
    path('legal/', views.legal, name='legal'),
    path('privacy/', views.privacy, name='privacy'),
    path('terms/', views.terms, name='terms'),
    path('security/', views.security, name='security'),
    path('fdic/', views.fdic, name='fdic'),
    path('contact/', views.contact, name='contact'),
    path('management/', views.custom_admin, name='custom_admin'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/profile/', views.profile, name='profile'),
    path('dashboard/verify/', views.verify, name='verify'),
    path('dashboard/transfer/', views.transfer, name='transfer'),
    path('dashboard/pay-bills/', views.pay_bills, name='pay_bills'),
    path('dashboard/statements/', views.statements, name='statements'),
    path('dashboard/transactions/', views.transactions, name='transactions'),
    path('dashboard/transactions/<int:pk>/', views.transaction_detail, name='transaction_detail'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/verify/approve/<int:user_id>/', views.approve_verification, name='approve_verification'),
    path('dashboard/verify/reject/<int:user_id>/', views.reject_verification, name='reject_verification'),
    path('api/send_chat/', views.send_chat, name='send_chat'),
    path('api/get_chats/', views.get_chats, name='get_chats'),
    path('management/chat/<int:user_id>/', views.admin_chat, name='admin_chat'),
    path('management/users/', views.all_users, name='all_users'),
    path('management/verifications/', views.verification_queue, name='verification_queue'),
    path('management/credit-user/', views.credit_user, name='credit_user'),
    path('management/api/recent-messages/', views.management_recent_messages_api, name='management_recent_messages_api'),
    path('management/verification/<int:user_id>/', views.verification_detail, name='verification_detail'),
    path('management/credit-history/', views.admin_credit_history, name='admin_credit_history'),
]
